### ISSUE TITLE
Ability to control LED indicators and buzzer

### ISSUE THREAD

**Issue by pokusew** [pokusew/nfc-pcsc#1]
Add support for controlling  LED indicators and buzzer on devices, where it is supported (e.g. ACR122 USB).

**Comment by pokusew** [comment]
Work in progress. Added basic support for ARC122 USB in [`led-control-support`](https://github.com/pokusew/nfc-pcsc/tree/led-control-support) branch.
Note, that APDU commands are different for different devices.

**Plan**
- [ ] wait for resolving pokusew/node-pcsclite#4: Expose vendorId and productId in reader object
- [ ] create new classes for supported readers

**Comment by indiecore-fm** [comment]
I'm not finding any ARC122 only ACR122, are they the same device?

**Comment by pokusew** [comment]
@indiecore-fm it is ACR122 (ARC122 does not exist, just a typo)

**Comment by pokusew** [comment]
Basic support for ACR122 added in https://github.com/pokusew/nfc-pcsc/commit/1477d2314dbbe49ca45587ecdba7efc2c39978c3 and published in [0.5.0](https://github.com/pokusew/nfc-pcsc/releases/tag/v0.5.0)
