### ISSUE TITLE
I don't understand that code

### ISSUE THREAD

**Issue by murat-sen-tr** [pokusew/nfc-pcsc#140]
https://github.com/pokusew/nfc-pcsc/blob/8f47cf9e623f45d8318a13460084068889f76ede/examples/utils.js#LL37-L49

**Comment by davidgs** [comment]
What don't you understand? This is far too vague of a question to be answered. Take some time (and read [this](https://www.freecodecamp.org/news/how-to-ask-good-technical-questions/) and you'll be more likely to get useful answers.
