### ISSUE TITLE
Is there any example to read Mifare 1K Card?

### ISSUE THREAD

**Issue by SuThaw** [pokusew/nfc-pcsc#2]

**Comment by pokusew** [comment]
Hi,

there is (and there was) a functional example of reading and writing card in https://github.com/pokusew/nfc-pcsc/blob/master/test/index.js.

I have improved the README to include these examples and added some comments how to use it, see [Reading and writing data](https://github.com/pokusew/nfc-pcsc#reading-and-writing-data).
I have also added useful info how cards handling works, see [Flow of handling tags](https://github.com/pokusew/nfc-pcsc#flow-of-handling-tags).

Cloud you please test if you are able to read Mifare 1K Card?
If everything works, I will close this issue.
