### ISSUE TITLE
Detect attached card reader on app start

### ISSUE THREAD

**Issue by Ionut-Milas** [pokusew/nfc-pcsc#46]
Hello @pokusew .
This is a great lib.

I'm using it on an Electron app with an ACS ACR1251 Dual Reader.

If I connect the reader after the app is started all is good, the reader is detected, but if the app starts and the reader is already connected to the PC, it does not register it.
Any help ?

**Comment by elia9090** [comment]
Hi Ionut,

how did you solve this issue??
