### ISSUE TITLE
Malformed SELECT FILE command?

### ISSUE THREAD

**Issue by martijnthe** [pokusew/nfc-pcsc#54]
Hi there, thanks for your library.

I'm having some trouble with an NXP NFC Tag type 4 tag (AID `D2760000850101`).
I inspected your code and compared it to another program that works correctly.

I noticed the code that sends the AID looks malformed:
https://github.com/pokusew/nfc-pcsc/blob/master/src/Reader.js#L736

According to [this source], there should be an `Lc` field containing the length of the (AID) data, prior to the AID data. There's a field that has a comment `Le` but it's hard-coded to `5`. Also, an empty / `00` byte (for the actual `Le`) seems to be missing.

What do you think?

[this source]: http://cardwerk.com/smart-card-standard-iso7816-4-section-6-basic-interindustry-commands/#chap6_11_3

**Comment by pokusew** [comment]
Hi @martijnthe,

**I think you are right!** 👍 

I looked into [the document](http://cardwerk.com/smart-card-standard-iso7816-4-section-6-basic-interindustry-commands/#chap6_11_3) you mentioned and the changes you described seem to be correct.

BTW – background info: _I wrote the `handle_Iso_14443_4_Tag` method to work with an Android HCE demo. In that time, I didn't understand the SELECT FILE command properly, I just tried to make it work. Then I added it to the library in hope of being useful for someone._ 😄

**Thank you very much for fixing it! I really appreciate that.** 🙂I accepted and merged your PR. Please answer my comment there.

Once the fixes are released into npm, please test if everything works for you and in case it doesn't reopen the issue. Thanks.

---

PS Thank you for the link to the free online copy of ISO 7816-4 standard. It's really hard to find relevant info about the standards. I'll be sure to add the corresponding links to the source code and to the documentation to make it clear where the commands come from, especially for beginners. 🙂 

---

PSS Don't forget to star ⭐️my library, if you find it useful. 😃Thanks.

**Comment by martijnthe** [comment]
You’re welcome :) thanks for accepting the fix!

**Comment by pokusew** [comment]
Hi @martijnthe, your fix along with many other shipped in [v0.7.0](https://github.com/pokusew/nfc-pcsc/releases/tag/v0.7.0). Please let me know if everything works for you as expected. 😉
