### ISSUE TITLE
node 12 / electron 5 compat

### ISSUE THREAD

**Issue by zy4** [pokusew/nfc-pcsc#81]
https://github.com/pokusew/node-pcsclite/pull/23

**Comment by bashoogzaad** [comment]
I also have the issue that electron-rebuild is failing because of v8 Handle being removed from Electron 5.

**Comment by pokusew** [comment]
@zy4 @bashoogzaad  Fixed and released in version [0.8.0](https://github.com/pokusew/nfc-pcsc/releases/tag/v0.8.0). 🎉
