### ISSUE TITLE
Cannot read string that is written from react native

### ISSUE THREAD

**Issue by jericopulvera** [pokusew/nfc-pcsc#93]
Hello, we've been using this package to read and write nfc tags in mobile and we're trying to read nfc data in web, but to no avail we can't read the data that is written from the mobile app.

This is the output

```
ACS ACR1252 1S CL Reader(2)  card removed { atr:
   <Buffer 3b 8f 80 01 80 4f 0c a0 00 00 03 06 03 00 01 00 00 00 00 6a>,
  standard: 'TAG_ISO_14443_3',
  type: 'TAG_ISO_14443_3',
  uid: 'ab27f824' }
```
Please point me in the right direction.

**Comment by Flamz23** [comment]
https://github.com/pokusew/nfc-pcsc#can-i-use-this-library-in-my-react-native-app
